### ISSUE TITLE
iWMO standaard bijwerken

### ISSUE THREAD

**Issue by Makkmetp** [VNG-Realisatie/GEMMA-Archi-repository#8]
De nieuwe versie van een iWMO standaard wordt jaarlijks rond 1 april met een big bang uitgerold, waardoor alle partijen daar direct aan moeten voldoen. Dit zorgt ervoor dat eerdere versies direct komen te vervallen en er maar één actuele versie is waar iedereen aan moet voldoen. 
Graag een versie met (actueel) aanmaken voor de iWMO standaard.

**Comment by markbacker** [comment]
De voor gemeenten relevante i-Standaarden staan op deze view. 

![2024-03-04 09_08_59-Clipboard](https://github.com/VNG-Realisatie/GEMMA-Archi-repository/assets/41415562/faa6fa9d-56d6-41e3-a996-d0a785a99931)
Deze i-standaarden hebben de standaardversie 'actueel'. Alle i-Standaarden genummerde versies hebben de status 'einde ondersteuning' gekregen.
